# Generated by Django 4.2.14 on 2025-06-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('parent_name', models.CharField(max_length=160)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('age_group', models.CharField(choices=[('Under 10 years', 'Under 10 years'), ('10-16 years', '10-16 years'), ('17+ years', '17+ years')], max_length=20)),
                ('mode_of_class', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('preferred_days', models.CharField(choices=[('Monday-Wednesday-Friday', 'Monday-Wednesday-Friday'), ('Tuesday-Thursday-Saturday', 'Tuesday-Thursday-Saturday')], max_length=30)),
                ('preferred_time', models.TimeField()),
                ('medium_of_arts', models.JSONField()),
            ],
        ),
    ]
