# Generated by Django 5.2.3 on 2025-06-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
